### ISSUE TITLE
Is it possible to set shard(:none) automatically for all migrations?

### ISSUE THREAD

**Issue by rodolfobandeira** [zendesk/active_record_shards#173]
Hi there,

I'm only using the `slave` config on my `database.yml`. I don't want to do anything related with shards for now. I'm wondering if there is a way to avoid [the raise exception](https://github.com/zendesk/active_record_shards/blob/master/lib/active_record_shards/migration.rb#L69-L72) that happens if we don't add that `shard(:none)` on each migration file. I was thinking to MonkeyPatch the `ActualMigrationExtension` and get rid of that. Is there other solution for this? 

Thank you

cc: @pschambacher, @bquorning, @grosser

**Comment by grosser** [comment]
`ActiveRecord::Migration.shard :none` might disable it ... otherwise monkey-patch away ... this library is not really supposed to be sued without sharding :)

**Comment by pschambacher** [comment]
You might also want to give a try to the beta of v4.0.0 which is a bit less automatic and requires manually switching to shards

**Comment by rodolfobandeira** [comment]
Thank you for the quick answer. I'll try it out your tips.
Cheers!
