### ISSUE TITLE
Bug: Additional connection pool is made when primary DB has no slave

### ISSUE THREAD

**Issue by bogdan** [zendesk/active_record_shards#177]
When the DB is configured without a slave in particular environment the connection name for non-sharded DB should be resolved as "primary" but not `Rails.env`.

The condition in this return doesn't cover the use case when slave is not configured for the environment:
https://github.com/zendesk/active_record_shards/blob/master/lib/active_record_shards/shard_selection.rb#L54

**Comment by bquorning** [comment]
Fixed by #185.
