### ISSUE TITLE
Thread Safe : (RuntimeError) Can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by pcodeblooded** [zendesk/active_record_shards#23]
Hi,

Very rarely we are getting Runtime Error. Please help us in finding the solution

```
class HardWorker < BaseWorker

  sidekiq_options :queue => :default, :retry => 0, :backtrace => true, :failures => :exhausted

  def perform(id)
    ActiveRecord::Base.on_shard(:shard_1) do
        10.times do 
          User.find(rand(1..10))
        end
    end
end

#Trace

~/.rvm/gems/ruby-1.9.3-p547@gemset1/gems/activerecord-2.3.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:296:in `[]='
~/.rvm/gems/ruby-1.9.3-p547@gemset1/gems/activerecord-2.3.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:296:in `establish_connection'
~/.rvm/gems/ruby-1.9.3-p547@gemset1/gems/active_record_shards-2.7.0/lib/active_record_shards/connection_switcher.rb:182:in `establish_shard_connection'
~/.rvm/gems/ruby-1.9.3-p547@gemset1/gems/active_record_shards-2.7.0/lib/active_record_shards/connection_switcher.rb:153:in `switch_connection'
~/.rvm/gems/ruby-1.9.3-p547@gemset1/gems/active_record_shards-2.7.0/lib/active_record_shards/connection_switcher.rb:15:in `on_shard'
~/project/app/workers/hard_worker.rb:6:in `perform'
```

We are planning to use the active_record_shards gem for sharding the database with sidekiq.

active_record_shard is Thread Safe ?

Rails - 2.318
Ruby - 1.9.3-p547
active_record_shards - 2.7.0
sidekiq - 3.0.0

Thanks

**Comment by alex-bezek** [comment]
I'm evaluating this gem for use on a project. I was wondering if there documentation on whether this gem is thread safe or not in rails 4.2 ? 
Thanks

**Comment by osheroff** [comment]
@alex-bezek we do have active_record_shards in production with rails 4.2 and a threaded server (puma).  We haven't experienced any thread safety issues with it, but be advised that this is a smaller service deployment than the "main" zendesk which uses ARS in a single-threaded mode.

**Comment by alex-bezek** [comment]
@osheroff  I will take this into account and inform my team.
Thanks a ton for the quick response.

**Comment by alex-bezek** [comment]
@vishal-jain we have been using it in a production service for the past 2 years. However, we don't utilize any threading in our rails service, and we are running passenger in a single thread + multi-process setup, so I'm not sure if that helps you out.

**Comment by vishal-jain** [comment]
@alex-bezek Thank you for the quick response. it's very helpful we are using the same architecture for application servers but for background processing, we are using Sidekiq so checking for thread safety.
