### ISSUE TITLE
Change the about text to say 'replicas' instead of 'slaves.

### ISSUE THREAD

**Issue by cornu-ammonis** [zendesk/active_record_shards#240]
Currently the about text which appears in e.g. Explore Repositories says `Support for sharded databases and slaves for ActiveRecord`. The word 'slave' used in this context can be disturbing and replica or follower is a more descriptive term. The readme says `ActiveRecord Shards is an extension for ActiveRecord that provides support for sharded database and replicas` so this change would also improve consistency.

**Comment by libo** [comment]
Thank you for surfacing this. We just changed please let me know if everything looks fine.

**Comment by cornu-ammonis** [comment]
Yep looks great. Thanks for addressing this quickly! 😄
