### ISSUE TITLE
Inconsistent readonly object

### ISSUE THREAD

**Issue by atitan** [zendesk/active_record_shards#241]
Hi there,

The readme indicates there are two kinds of usage of `on_replica`.
```
ActiveRecord::Base.on_replica do
  Account.find_by_big_expensive_query
end

Account.on_replica.find_by_big_expensive_query
```

I think they should both return readonly objects, but it turned out only the latter one is readonly.

```
ActiveRecord::Base.on_replica do
  Account.find_by_big_expensive_query.readonly?
end
=> false

Account.find_by_big_expensive_query.readonly?
=> true
```

Did I miss something here?

Environment:
-  active_record_shards: git master
-  rails: 4.2

**Comment by grosser** [comment]
the second case fetches the objects from reader, but there is no real reason that it cannot be modified ... so we never added that restriction/feature ... also don't feel like every user wants that, since reading from read-only and then writing seems like a reasonable usecase
